### ISSUE TITLE
[SPRINT] DESC Note re DESC cohesive DDF strategy

### ISSUE THREAD

**Issue by humnaawan** [LSSTDESC/SprintDaySLAC2023#17]
# DESC Note re DESC cohesive DDF strategy

We'd like to start putting together a DESC Note re DESC cohesive DDF strategy.

Contacts: @pgris 
Time: TBA, depending on who's interested
Main communication channel: #desc-cohesive-ddf-strategy
In-person/Virtual/Hybrid: TBA, depending on who's interested

## Goals and deliverable

- Start an outline of the DESC Note, documenting all the recent development.
- Make clear any outstanding todos.

## Resources and skills needed

Interest in LSST DDF optimization for DESC needs.

## Detailed description

There has been quite a bit of work going on re devising a cohesive Deep Drilling Fields (DDF) strategy that works for various science cases, including SN, WL, PZ - and we'd like to document it.

(TBA: DESC project link)

**Comment by pgris** [comment]
The DESC project link for this sprint: https://portal.lsstdesc.org/DESCPub/app/PB/show_project?pid=329
